# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('nascimento', models.DateField(default=datetime.datetime.today)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('data_solicitacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inativado', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name': 'dados_familia',
                'verbose_name_plural': 'Dados das Familias',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especialidades',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.AddField(
            model_name='dadosfamilia',
            name='necessidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.Especialidades'),
        ),
    ]
