# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_dadosfamilia_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfamilia',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='estado',
            field=models.CharField(default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosfamilia',
            name='telefone',
            field=models.CharField(max_length=100),
        ),
    ]
