# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 23:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valorUnitario', models.DecimalField(decimal_places=6, max_digits=20)),
                ('rateio', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compras',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fixa', models.BooleanField(default=False)),
                ('dtLancamento', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name': 'Despesas',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Despesas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato',
                'verbose_name_plural': 'Extratos',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notafiscal', models.FileField(blank=True, null=True, upload_to='cupons')),
                ('url_qrcode', models.URLField(blank=True, max_length=1000, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notas',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Rateios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Despesas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rateio',
                'verbose_name_plural': 'Rateios',
            },
        ),
    ]
