# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateField(),
        ),
    ]
